
# Configuring the property file in this YAML extension (switching form applicaiton.properties)

spring:
  datasource:
    url:jdbc: mysql://localhost:3306/mydb
    username: root
    password: MySQL@#0012
  jpa:
    show-sql: true

server:
  servlet:
    context-path: /productapi

springdoc:
  swagger-ui:
    path: /swaggerui